title:
  MetaMut
description:
  A mutation operator generator to facilitate compiler fuzzing.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - README.ubuntu.md
  - bugs.md
permissions:
  id-token: write
  pages: write
repository: https://github.com/icsnju/MetaMut

theme: jekyll-theme-merlot
