plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - README.ubuntu.md
  - bugs.md
permissions:
  id-token: write
  pages: write

theme: jekyll-theme-tactile
